apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "secret-runtime-keys") }}
type: Opaque
data:
{{- if not (empty .Values.github.integration_private_key_path) }}
  github.pem: {{ (.Files.Get .Values.github.integration_private_key_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.firebase.service_account_path) }}
  firebase.json: {{ (.Files.Get .Values.firebase.service_account_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.jwt.private_key_path) }}
  jwt-private.pem: {{ (.Files.Get .Values.jwt.private_key_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.jwt.public_key_path) }}
  jwt-public.pem: {{ (.Files.Get .Values.jwt.public_key_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.ssl.private_key_path) }}
  server.key: {{ (.Files.Get .Values.ssl.private_key_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.ssl.certificate_path) }}
  server.crt: {{ (.Files.Get .Values.ssl.certificate_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.google_cloud_audit.service_account_path) }}
  google-cloud-audit-log.json: {{ (.Files.Get .Values.google_cloud_audit.service_account_path) | b64enc }}
{{- end }}
{{- if not (empty .Values.gcb.service_account_path) }}
  google-cloud-builder.json: {{ (.Files.Get .Values.gcb.service_account_path) | b64enc }}
{{- end }}
