apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: rabbitmq
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "rabbitmq") }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "continuouspipe.name" . }}
        release: {{ .Release.Name }}
        component: rabbitmq
    spec:
      restartPolicy: Always
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_NODE_NAME
              value: localhost
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq"
              name: rabbitmq-data-volume
      volumes:
        - name: rabbitmq-data-volume
          persistentVolumeClaim:
            claimName: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "rabbitmq-claim") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: rabbitmq
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "rabbitmq") }}
spec:
  ports:
    - name: rabbitmq
      port: 5672
    - name: management
      port: 15672
  selector:
    app: {{ template "continuouspipe.name" . }}
    release: {{ .Release.Name }}
    component: rabbitmq
