apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: redis
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "redis") }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "continuouspipe.name" . }}
        release: {{ .Release.Name }}
        component: redis
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:alpine
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: redis
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "redis") }}
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: {{ template "continuouspipe.name" . }}
    release: {{ .Release.Name }}
    component: redis
