apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ui
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "ui") }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "continuouspipe.name" . }}
        release: {{ .Release.Name }}
        component: ui
    spec:
      restartPolicy: Always
      containers:
      - image: docker.io/continuouspipe/ui:latest
        imagePullPolicy: Always
        name: ui
        envFrom:
        - configMapRef:
            name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "main-config") }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 30
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "continuouspipe.name" . }}
    chart: {{ template "continuouspipe.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ui
  name: {{ template "continuouspipe.component_name" (dict "Release" .Release "Component" "ui") }}
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 80
  selector:
    app: {{ template "continuouspipe.name" . }}
    release: {{ .Release.Name }}
    component: ui
